sudo: required
services:
  - docker

before_install:
  - docker build -t shihyen/docker-react -f Dockerfile.dev . 

script:
  - docker run shihyen/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "northeast-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket: "S3 Bucket"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"